### PR TITLE
Adds autocorrect and many more checks 

### PR DESCRIPTION
**Pull request by stevenweber**
It also upgrades Rubocop to take advantage of the Base class and adds ActiveSupport as a dependency to do accurate corrections, e.g. underscore/camel/pascal casing.

### CODE REVIEW

**Review by iMacTia — APPROVED** [review]
Fantastic work @stevenweber, really looking forward to get this merged 🤞!

**Comment by stevenweber** [comment]
@aergonaut please let me know if you have any questions or concerns that I can address about this PR.

**Comment by aergonaut** [comment]
@stevenweber Thanks for this. Apologies for not responding sooner. I will take a look and let you know.

**Comment by stevenweber** [comment]
@aergonaut are you still thinking this will get merged?

**Review by aergonaut — APPROVED** [review]
Sorry for falling off this again! This looks great 👍

**Comment by stevenweber** [comment]
Awesome. Do you mind creating a release with the changes?

**Pull request merged**
